# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  server:
    profiles: ["prod"]
    env_file: 
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-manager-frontend
    # NODE_ENV: production could be uncommented in environment if needed
    ports:
      - 3000:3000

  server-dev:
    profiles: ["dev"]
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: task-manager-frontend-dev
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
