apiVersion: v1
kind: Service
metadata: # Metadata for the service
  name: task-manager-frontend-service # Name of the service
spec: # Specifies the desired state for the service
  selector: # Selects the pods managed by this service
    app: task-manager-frontend # Labels for the pods
  ports: # Ports for the service
    - protocol: TCP
      port: 3000 # The port that the service will expose
      targetPort: 3000 # The port on the container that the service will forward to
  type: NodePort # Expose the service on a port on each node in the cluster